#!/bin/bash
set -euo pipefail
cd "$( dirname "${BASH_SOURCE[0]}" )"
source ../../meta/repeatr.sh

danggit_hash="$(git rev-parse HEAD)"
sudo bash -c "$repeatr run $rciflags <(sed "s/%%PLACEHOLDER%%/$danggit_hash/" *.formula)"
